languageCode = "en"
languageName = "English"
weight = 1
title = "Trophy World"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/trophyworld.png"
  secondaryLogo = "img/trophyworld.png"
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Trophy World Gosford"
  image = "img/trophyworld.png"
  headline = "Trophy World are your specialists in laser and conventional engraving, corporate awards and trophies for all occasions."
  bio = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  links = [
    { email = "mailto:enquiry@trophyworldgosford.com.au" },
    { facebook = "https://facebook.com/trophyworld" },
  #  { linkedin = "https://linkedin.com/in/username" },
  #  { x-twitter = "https://twitter.com/username" },
  #  { github = "https://github.com/username" },
    #{ medium = "https://medium.com/@username" },
    #{ hackernews = "https://news.ycombinator.com/user?id=username"},
    #{ mastodon = "https://masto.ai/@username" },
    { instagram = "https://instagram.com/trophyworldgosford" },
  #  { goodreads = "http://goodreads.com/username" },
    #{ keybase = "https://keybase.io/trophyworld" },
    #{ reddit = "https://reddit.com/user/trophyworld" },
    #{ telegram = "https://t.me/trophyworld" },
    #{ music = "/music" },

  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
  ]
